// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manually creating a sidebar with SDKs & Release Versions section
  sdkReleaseSidebar: [
    {
      type: 'category',
      label: 'SDKs & Release Versions',
      items: [
        'robots-sdk',   // Reference to Robot SDKs & Release Versions page
        'grippers-sdk', // Reference to Grippers SDKs & Release Versions page
        'camera-sdk',  // Reference to Camera SDKs & Release Versions page
      ],
    },
  ],

  // Optionally, add other sidebar categories if needed
};

export default sidebars;
